services:
  cofoundnet:
    container_name: CoFoundNet
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000" # Traefik will handle routing, no need to expose port 3000 directly
    environment:
      - NODE_ENV=production
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cofoundnet.rule=Host(`31.97.193.81`)"
      - "traefik.http.routers.cofoundnet.entrypoints=web"
      - "traefik.http.services.cofoundnet.loadbalancer.server.port=3000"
    networks:
      - traefik_public
      - default

networks:
  traefik_public:
    external: true # Assumes you have an existing network named 'traefik_public'
