services:
  cofoundnet:
    container_name: CoFoundNet
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: always
    expose:
      - "3000"
    networks:
      - cofoundnet_network

  nginx:
    image: nginx:alpine
    container_name: CoFoundNet_Nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cofoundnet
    restart: always
    networks:
      - cofoundnet_network

networks:
  cofoundnet_network:
    driver: bridge
